namespace: lak-test

backend:
  replicaCount: 1
  image:
    repository: lakshan31/lakshoppinglist-backend
    tag: v1
    pullPolicy: Always
  service:
    port: 5000

frontend:
  replicaCount: 2
  image:
    repository: lakshan31/lakshoppinglist-frontend
    tag: v1
    pullPolicy: Always
  service:
    type: NodePort
    port: 80

postgres:
  replicaCount: 1
  image:
    repository: postgres
    tag: "16"
    pullPolicy: IfNotPresent
  service:
    port: 5432
  auth:
    database: shoppinglist
    username: postgres
    password: postgres
  storage:
    size: 1Gi