apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: shopping-stateful
spec:
  serviceName: "shopping"
  replicas: 3
  selector:
    matchLabels:
      app: shopping
  template:
    metadata:
      labels:
        app: shopping
    spec:
      containers:
      - name: shopping-container
        image: shopping-app
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
