apiVersion: v1
kind: Service
metadata:
  name: lak-backend-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: lak-backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 5000
