apiVersion: apps/v1
kind: Deployment
metadata:
  name: lak-backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: lak-backend
  template:
    metadata:
      labels:
        app: lak-backend
    spec:
      containers:
        - name: lak-backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: 5000