apiVersion: apps/v1
kind: Deployment
metadata:
  name: lak-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: lak-frontend
  template:
    metadata:
      labels:
        app: lak-frontend
    spec:
      containers:
        - name: lak-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 80
